# Generated by Django 6.0 on 2025-12-26 01:06

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(help_text='URL uchun nom', unique=True)),
                ('description', ckeditor.fields.RichTextField(verbose_name='Kurs haqida batafsil')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Kurs rasmi')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Hozirgi narxi (Sotuvdagi)')),
                ('old_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Eski narxi (Chegirma uchun)')),
                ('telegram_group_link', models.URLField(blank=True, null=True, verbose_name='Yopiq Guruh Linki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Dars mavzusi')),
                ('slug', models.SlugField(help_text='URL uchun')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Dars raqami')),
                ('video_link', models.URLField(verbose_name='Video Dars Linki (Telegram)')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Dars matni va Qoidalar')),
                ('homework_description', ckeditor.fields.RichTextField(blank=True, verbose_name='Uyga vazifa sharti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Promokod (Masalan: NAVRUZ2025)')),
                ('discount_percentage', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma foizi (%)')),
                ('valid_from', models.DateTimeField(verbose_name='Amal qilish boshlanishi')),
                ('valid_to', models.DateTimeField(verbose_name='Amal qilish tugashi')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivmi?')),
                ('allowed_courses', models.ManyToManyField(blank=True, to='courses.course', verbose_name='Qaysi kurslarga amal qiladi?')),
            ],
            options={
                'verbose_name': 'Promokod',
                'verbose_name_plural': 'Promokodlar',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='homeworks/', verbose_name='Vazifa fayli')),
                ('text_answer', models.TextField(blank=True, null=True, verbose_name='Yozma javob')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Qabul qilindimi?')),
                ('admin_comment', models.TextField(blank=True, null=True, verbose_name="O'qituvchi izohi")),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Vazifa Javobi',
                'verbose_name_plural': 'Vazifa Javoblari',
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_receipt', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name="To'lov cheki")),
                ('status', models.CharField(choices=[('pending', 'Tekshirilmoqda'), ('active', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Holati')),
                ('final_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name="To'langan summa")),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('used_promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.promocode', verbose_name='Ishlatilgan Promokod')),
            ],
            options={
                'verbose_name': "A'zolik (To'lov)",
                'verbose_name_plural': "A'zolar va To'lovlar",
                'unique_together': {('user', 'course')},
            },
        ),
    ]
